# Generated by Django 4.2.2 on 2023-06-26 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_rename_shows_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='Genres',
            new_name='Genre',
        ),
    ]
