# Generated by Django 4.2.2 on 2023-06-27 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_category_remove_show_genre_show_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='Cover_Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
