# Generated by Django 4.2.2 on 2023-06-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_alter_category_id_alter_show_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='Cover_Image',
        ),
    ]
