# Generated by Django 4.2.2 on 2023-07-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_show_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='youtubeVideoKey',
            field=models.CharField(max_length=20000, null=True, verbose_name='Youtube trailer video id'),
        ),
        migrations.AlterField(
            model_name='show',
            name='Cover_Image',
            field=models.ImageField(max_length=2000, null=True, upload_to='images/'),
        ),
    ]
