# Generated by Django 4.2.2 on 2023-07-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0011_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='number_ep',
        ),
        migrations.AddField(
            model_name='movie',
            name='Runtime',
            field=models.CharField(default=1, max_length=120, verbose_name='Runtime(min)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='Name',
            field=models.CharField(max_length=120, verbose_name='Movie Name'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Movie Summary'),
        ),
    ]
