# Generated by Django 4.2.2 on 2023-07-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0012_remove_movie_number_ep_movie_runtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_name',
            new_name='Genre',
        ),
    ]
