# Generated by Django 4.2.2 on 2023-07-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0016_profile_watching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
