# Generated by Django 4.2.2 on 2023-07-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0017_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backgroundcolor',
            field=models.CharField(default='black', max_length=120000, verbose_name='backgroundcolor'),
        ),
    ]
