# Generated by Django 4.2.4 on 2023-10-27 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0030_alter_showrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showrating',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
