# Generated by Django 4.2.4 on 2023-10-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0035_alter_showcomments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcomments',
            name='date_added',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
