# Generated by Django 4.2.4 on 2023-11-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0036_showcomments_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='watching',
            field=models.ManyToManyField(null=True, to='shows.show'),
        ),
    ]
