# Generated by Django 4.2.2 on 2023-06-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_show_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='Cover_Image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
