# Generated by Django 4.2.2 on 2023-07-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_show_youtubevideokey_alter_show_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=120, verbose_name='Show Name')),
                ('number_ep', models.CharField(max_length=120, verbose_name='Number of Episodes')),
                ('summary', models.TextField(blank=True, verbose_name='Show Summary')),
                ('Cover_Image', models.ImageField(max_length=2000, null=True, upload_to='images/')),
                ('youtubeVideoKey', models.CharField(max_length=20000, null=True, verbose_name='Youtube trailer video id')),
                ('Genre', models.ManyToManyField(to='shows.category')),
            ],
        ),
    ]
