# Generated by Django 4.2.2 on 2023-07-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0014_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Bio',
            field=models.CharField(max_length=120000, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Profile_Image',
            field=models.ImageField(max_length=2000, null=True, upload_to='images/', verbose_name='Profile Picture'),
        ),
    ]
