# Generated by Django 4.2.2 on 2023-07-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0015_profile_bio_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watching',
            field=models.ManyToManyField(to='shows.show'),
        ),
    ]
