# Generated by Django 4.2.4 on 2023-10-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0026_showrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showrating',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
