# Generated by Django 4.2.4 on 2023-10-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0034_showcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcomments',
            name='comment',
            field=models.TextField(max_length=255, verbose_name='comment'),
        ),
    ]
